# version: "3.8"

services:
  server:
    build: ./server
    container_name: socket_server
    ports:
      - "5000:5000"

  client:
    build: ./client
    container_name: socket_client
    depends_on:
      - server
